"""
Fix Vietnamese diacritics in anchor-index.md
Strategy:
  1. For each Live Published row, strip ALL existing diacritics from anchor text (normalize to ASCII)
  2. Apply ordered multi-word → single-word replacements to restore proper diacritics
  3. Rebuild the keywords column as: [fixed_anchor], kiến thức DSC
  Finalized rows are left untouched.
"""
import re
import sys
import unicodedata

INPUT_FILE = r"e:\project\seo-writer-agent-main\knowledge\3-pipeline\anchor-index.md"
OUTPUT_FILE = INPUT_FILE

# Vietnamese diacritic removal map (uppercase + lowercase)
VIET_MAP = str.maketrans(
    'àáảãạăắặằẳẵâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừửữựỳýỷỹỵđ'
    'ÀÁẢÃẠĂẮẶẰẲẴÂẤẦẨẪẬÈÉẺẼẸÊẾỀỂỄỆÌÍỈĨỊÒÓỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÙÚỦŨỤƯỨỪỬỮỰỲÝỶỸỴĐ',
    'aaaaaaaaaaaaaaaaaeeeeeeeeeeeiiiiiooooooooooooooooouuuuuuuuuuuyyyyyd'
    'AAAAAAAAAAAAAAAAAEEEEEEEEEEEIIIIIOOOOOOOOOOOOOOOOOUUUUUUUUUUUYYYYYD',
)


def remove_viet_diacritics(text: str) -> str:
    return text.translate(VIET_MAP)


# Replacement rules: longest/most-specific multi-word phrases first, then shorter.
# All patterns use non-accented Vietnamese (since we strip diacritics first).
REPLACEMENTS = [
    # Specific full-sentence patterns (most specific first)
    ("20 nguyen tac giao dich cua richard donchian", "20 nguyên tắc giao dịch của Richard Donchian"),
    ("1 trieu co choi duoc chung khoan khong", "1 triệu có chơi được chứng khoán không"),
    ("3 cach chon co phieu tot va co tiem nang tang gia de dau tu", "3 cách chọn cổ phiếu tốt và có tiềm năng tăng giá để đầu tư"),
    ("5 chi so quan trong cua phan tich co ban trong chung khoan", "5 chỉ số quan trọng của phân tích cơ bản trong chứng khoán"),
    ("5 cach dau tu tien ao tu a z cho f0 tranh mat tien", "5 cách đầu tư tiền ảo từ A đến Z cho F0 tránh mất vốn"),
    # B
    ("bat dau", "bắt đầu"),
    ("bien do giao dong gia co phieu la gi", "biên độ giao động giá cổ phiếu là gì"),
    ("bien do giao dich san chung khoan hose hnx upcom", "biên độ giao dịch sàn chứng khoán HOSE HNX UPCOM"),
    ("bien do giao dich", "biên độ giao dịch"),
    ("bien do giao dong", "biên độ giao động"),
    ("bien do", "biên độ"),
    ("bien dong", "biến động"),
    ("bien loi nhuan gop la gi y nghia cua bien loi nhuan gop khi lua chon co phieu", "biên lợi nhuận gộp là gì ý nghĩa của biên lợi nhuận gộp khi lựa chọn cổ phiếu"),
    ("bien loi nhuan gop la gi y nghia cua bien loi nhuan gop", "biên lợi nhuận gộp là gì ý nghĩa của biên lợi nhuận gộp"),
    ("bien loi nhuan gop", "biên lợi nhuận gộp"),
    ("bien loi nhuan rong net profit margin la gi giai dap chi tiet va y nghia quan trong", "biên lợi nhuận ròng net profit margin là gì giải đáp chi tiết và ý nghĩa quan trọng"),
    ("bien loi nhuan rong", "biên lợi nhuận ròng"),
    ("bien loi nhuan", "biên lợi nhuận"),
    ("bieu do chung khoan la gi cach xem bieu do chung khoan", "biểu đồ chứng khoán là gì cách xem biểu đồ chứng khoán"),
    ("bieu do nen chung khoan cho nguoi moi bat dau", "biểu đồ nến chứng khoán cho người mới bắt đầu"),
    ("bieu do nen", "biểu đồ nến"),
    ("bieu do", "biểu đồ"),
    ("bom tien ra nen kinh te la gi tac dong cua bom tien den ttck", "bơm tiền ra nền kinh tế là gì tác động của bơm tiền đến TTCK"),
    ("bom tien ra nen kinh te", "bơm tiền ra nền kinh tế"),
    ("bom tien", "bơm tiền"),
    ("bong bong dotcom la gi", "bong bóng dotcom là gì"),
    ("bong bong", "bong bóng"),
    # C
    ("cac chi so chung khoan chau a noi bat", "các chỉ số chứng khoán châu Á nổi bật"),
    ("cac chi so chung khoan viet nam hieu ro ve vn index vn 30 hnx index va nhieu chi so khac", "các chỉ số chứng khoán Việt Nam hiểu rõ về VN-Index VN-30 HNX-Index và nhiều chỉ số khác"),
    ("cac chi so phan tich bao cao tai chinh quan trong nhat cho nha dau tu", "các chỉ số phân tích báo cáo tài chính quan trọng nhất cho nhà đầu tư"),
    ("cac chi so phan tich bao cao tai chinh", "các chỉ số phân tích báo cáo tài chính"),
    ("cac chi so", "các chỉ số"),
    ("cac co phieu niem yet thuoc tap doan vingroup danh sach day du va cap nhat nam 2024", "các cổ phiếu niêm yết thuộc tập đoàn Vingroup danh sách đầy đủ và cập nhật năm 2024"),
    ("cac cong cu tai chinh pho bien tai viet nam", "các công cụ tài chính phổ biến tại Việt Nam"),
    ("cac loai tai khoan chung khoan pho bien tai viet nam", "các loại tài khoản chứng khoán phổ biến tại Việt Nam"),
    ("cac loai tai khoan", "các loại tài khoản"),
    ("cac loai", "các loại"),
    ("cac quy dinh giao dich chung khoan quan trong ma nguoi moi can biet", "các quy định giao dịch chứng khoán quan trọng mà người mới cần biết"),
    ("cac quy dinh", "các quy định"),
    ("cac thuat ngu trong chung khoan", "các thuật ngữ trong chứng khoán"),
    ("cac", "các"),
    ("call margin la gi lam gi khi bi call margin", "call margin là gì làm gì khi bị call margin"),
    ("cam nang a z cho f0", "cẩm nang A-Z cho F0"),
    ("cam nang", "cẩm nang"),
    ("can can thanh toan bop la gi", "cán cân thanh toán BOP là gì"),
    ("can can thuong mai la gi vai tro va tac dong den nen kinh te", "cán cân thương mại là gì vai trò và tác động đến nền kinh tế"),
    ("can can thuong mai", "cán cân thương mại"),
    ("can can vang lai la gi", "cán cân vãng lai là gì"),
    ("can can", "cán cân"),
    ("can biet", "cần biết"),
    ("cap nhat ket qua kinh doanh moi nhat", "cập nhật kết quả kinh doanh mới nhất"),
    ("cap nhat ket qua", "cập nhật kết quả"),
    ("cap nhat", "cập nhật"),
    ("cap nhan ket qua", "cập nhận kết quả"),
    ("cat lo la gi", "cắt lỗ là gì"),
    ("cat lo", "cắt lỗ"),
    ("cau tien la gi tac dong cua cau tien toi nen kinh te va thi truong chung khoan", "cầu tiền là gì tác động của cầu tiền tới nền kinh tế và thị trường chứng khoán"),
    ("cau tien la gi", "cầu tiền là gì"),
    ("cau tien", "cầu tiền"),
    ("cach ap dung chien luoc buy the dips", "cách áp dụng chiến lược buy the dips"),
    ("cach ap dung de tim doanh nghiep dang bi dinh gia thap", "cách áp dụng để tìm doanh nghiệp đang bị định giá thấp"),
    ("cach ap dung de tim co phieu tot", "cách áp dụng để tìm cổ phiếu tốt"),
    ("cach ap dung vao phan tich co ban co phieu", "cách áp dụng vào phân tích cơ bản cổ phiếu"),
    ("cach ap dung", "cách áp dụng"),
    ("cach ban co phieu cho nguoi moi", "cách bán cổ phiếu cho người mới"),
    ("cach chon co phieu tot va co tiem nang tang gia de dau tu", "cách chọn cổ phiếu tốt và có tiềm năng tăng giá để đầu tư"),
    ("cach choi chung khoan cho sinh vien", "cách chơi chứng khoán cho sinh viên"),
    ("cach choi chung khoan", "cách chơi chứng khoán"),
    ("cach dau tu chung khoan cho nguoi moi bat dau", "cách đầu tư chứng khoán cho người mới bắt đầu"),
    ("cach dinh gia co phieu cho nguoi moi bat dau", "cách định giá cổ phiếu cho người mới bắt đầu"),
    ("cach doc bieu do nen chung khoan cho nguoi moi bat dau", "cách đọc biểu đồ nến chứng khoán cho người mới bắt đầu"),
    ("cach doc bieu do nen", "cách đọc biểu đồ nến"),
    ("cach mo tai khoan chung khoan my", "cách mở tài khoản chứng khoán Mỹ"),
    ("cach mua co phieu online cho nguoi moi bat dau", "cách mua cổ phiếu online cho người mới bắt đầu"),
    ("cach mua co phieu tren san hnx", "cách mua cổ phiếu trên sàn HNX"),
    ("cach mua co phieu tren san hose", "cách mua cổ phiếu trên sàn HOSE"),
    ("cach mua co phieu tren san upcom", "cách mua cổ phiếu trên sàn UPCOM"),
    ("cach mua co phieu hoa phat hpg nhanh chong va an toan", "cách mua cổ phiếu Hòa Phát HPG nhanh chóng và an toàn"),
    ("cach mua co phieu vingroup vic huong dan moi nhat 2024", "cách mua cổ phiếu Vingroup VIC hướng dẫn mới nhất 2024"),
    ("cach mua co phieu vinamilk vnm cho nguoi moi bat dau", "cách mua cổ phiếu Vinamilk VNM cho người mới bắt đầu"),
    ("cach mua co phieu fpt cong ty co phan tap doan fpt", "cách mua cổ phiếu FPT công ty cổ phần tập đoàn FPT"),
    ("cach mua co phieu plx petrolimex", "cách mua cổ phiếu PLX Petrolimex"),
    ("cach mua co phieu bid", "cách mua cổ phiếu BID"),
    ("cach mua co phieu bvh", "cách mua cổ phiếu BVH"),
    ("cach mua co phieu ctg", "cách mua cổ phiếu CTG"),
    ("cach mua co phieu flc", "cách mua cổ phiếu FLC"),
    ("cach mua co phieu gvr", "cách mua cổ phiếu GVR"),
    ("cach mua co phieu hdb", "cách mua cổ phiếu HDB"),
    ("cach mua co phieu ipo", "cách mua cổ phiếu IPO"),
    ("cach mua co phieu nvl", "cách mua cổ phiếu NVL"),
    ("cach mua co phieu pow", "cách mua cổ phiếu POW"),
    ("cach mua co phieu pvd", "cách mua cổ phiếu PVD"),
    ("cach mua co phieu sab", "cách mua cổ phiếu SAB"),
    ("cach mua co phieu shb", "cách mua cổ phiếu SHB"),
    ("cach mua co phieu stb", "cách mua cổ phiếu STB"),
    ("cach mua co phieu tpb", "cách mua cổ phiếu TPB"),
    ("cach mua co phieu vhm", "cách mua cổ phiếu VHM"),
    ("cach mua co phieu vjc", "cách mua cổ phiếu VJC"),
    ("cach mua co phieu vre", "cách mua cổ phiếu VRE"),
    ("cach mua co phieu", "cách mua cổ phiếu"),
    ("cach phan tich bao cao tai chinh", "cách phân tích báo cáo tài chính"),
    ("cach su dung 4 duong ma pho bien trong phan tich ky thuat", "cách sử dụng 4 đường MA phổ biến trong phân tích kỹ thuật"),
    ("cach su dung", "cách sử dụng"),
    ("cach tinh va y nghia cua he so nay", "cách tính và ý nghĩa của hệ số này"),
    ("cach tinh", "cách tính"),
    ("cach xac dinh va phong tranh trong phan tich ky thuat", "cách xác định và phòng tránh trong phân tích kỹ thuật"),
    ("cach xac dinh", "cách xác định"),
    ("cach xem bieu do chung khoan", "cách xem biểu đồ chứng khoán"),
    ("cach", "cách"),
    ("chay tai khoan chung khoan la gi", "cháy tài khoản chứng khoán là gì"),
    ("chay tai khoan", "cháy tài khoản"),
    ("chi phi bien la gi", "chi phí biến là gì"),
    ("chi phi co dinh la gi tim hieu chi tiet ve chi phi co dinh trong kinh doanh", "chi phí cố định là gì tìm hiểu chi tiết về chi phí cố định trong kinh doanh"),
    ("chi phi co dinh", "chi phí cố định"),
    ("chi phi co hoi la gi", "chi phí cơ hội là gì"),
    ("chi phi von capex la gi y nghia va cach tinh chi phi von", "chi phí vốn capex là gì ý nghĩa và cách tính chi phí vốn"),
    ("chi phi von capex", "chi phí vốn capex"),
    ("chi phi von", "chi phí vốn"),
    ("chi phi", "chi phí"),
    ("chi so bien dong vix la gi", "chỉ số biến động VIX là gì"),
    ("chi so chung khoan la gi", "chỉ số chứng khoán là gì"),
    ("chi so chung khoan chau a noi bat", "chỉ số chứng khoán châu Á nổi bật"),
    ("chi so chung khoan viet nam hieu ro ve vn index vn 30 hnx index va nhieu chi so khac", "chỉ số chứng khoán Việt Nam hiểu rõ về VN-Index VN-30 HNX-Index và nhiều chỉ số khác"),
    ("chi so chung khoan", "chỉ số chứng khoán"),
    ("chi so dow jones la gi y nghia cua chi so dow jones", "chỉ số Dow Jones là gì ý nghĩa của chỉ số Dow Jones"),
    ("chi so dow jones future la gi", "chỉ số Dow Jones Future là gì"),
    ("chi so dow jones", "chỉ số Dow Jones"),
    ("chi so hang seng index la gi", "chỉ số Hang Seng Index là gì"),
    ("chi so hnx 30 la gi", "chỉ số HNX 30 là gì"),
    ("chi so hnx index la gi", "chỉ số HNX Index là gì"),
    ("chi so ldr la gi", "chỉ số LDR là gì"),
    ("chi so msci la gi", "chỉ số MSCI là gì"),
    ("chi so nasdaq chi so chung khoan cong nghe hang dau the gioi", "chỉ số NASDAQ chỉ số chứng khoán công nghệ hàng đầu thế giới"),
    ("chi so nikkei la gi", "chỉ số Nikkei là gì"),
    ("chi so npv la gi", "chỉ số NPV là gì"),
    ("chi so p b la gi cach ap dung de tim doanh nghiep dang bi dinh gia thap", "chỉ số P/B là gì cách áp dụng để tìm doanh nghiệp đang bị định giá thấp"),
    ("chi so p e la gi cach ap dung de tim co phieu tot", "chỉ số P/E là gì cách áp dụng để tìm cổ phiếu tốt"),
    ("chi so pmi la gi", "chỉ số PMI là gì"),
    ("chi so ppi la gi", "chỉ số PPI la gì"),
    ("chi so roa la gi y nghia va cach su dung", "chỉ số ROA là gì ý nghĩa và cách sử dụng"),
    ("chi so roic la gi", "chỉ số ROIC là gì"),
    ("chi so ros la gi", "chỉ số ROS là gì"),
    ("chi so rs la gi", "chỉ số RS là gì"),
    ("chi so s p 500 la gi", "chỉ số S&P 500 là gì"),
    ("chi so san xuat cong nghiep iip la gi", "chỉ số sản xuất công nghiệp IIP là gì"),
    ("chi so set la gi", "chỉ số SET là gì"),
    ("chi so shanghai la gi", "chỉ số Shanghai là gì"),
    ("chi so vn index va y nghia quan trong trong thi truong chung khoan viet nam", "chỉ số VN-Index và ý nghĩa quan trọng trong thị trường chứng khoán Việt Nam"),
    ("chi tieu loi nhuan cua doanh nghiep", "chỉ tiêu lợi nhuận của doanh nghiệp"),
    ("chia tach co phieu la gi muc dich cua viec chia tach co phieu", "chia tách cổ phiếu là gì mục đích của việc chia tách cổ phiếu"),
    ("chien luoc buy the dips", "chiến lược buy the dips"),
    ("chien luoc", "chiến lược"),
    ("choi chung khoan co giau khong", "chơi chứng khoán có giàu không"),
    ("choi chung khoan cho sinh vien", "chơi chứng khoán cho sinh viên"),
    ("choi chung khoan", "chơi chứng khoán"),
    ("chu ky co phieu la gi", "chu kỳ cổ phiếu là gì"),
    ("chu ky la gi", "chu kỳ là gì"),
    ("chu ky", "chu kỳ"),
    ("chung chi cfa la gi", "chứng chỉ CFA là gì"),
    ("chung chi cmt la gi", "chứng chỉ CMT là gì"),
    ("chung chi hanh nghe chung khoan la gi", "chứng chỉ hành nghề chứng khoán là gì"),
    ("chung chi hanh nghe", "chứng chỉ hành nghề"),
    ("chung chi tai chinh", "chứng chỉ tài chính"),
    ("chung chi", "chứng chỉ"),
    ("chung khoan la gi nhung dieu can biet truoc khi tham gia thi truong chung khoan", "chứng khoán là gì những điều cần biết trước khi tham gia thị trường chứng khoán"),
    ("chuyen vien tai chinh la gi", "chuyên viên tài chính là gì"),
    ("chuyen vien tai chinh", "chuyên viên tài chính"),
    ("co ban trong chung khoan", "cơ bản trong chứng khoán"),
    ("co cau von capital structure la gi cach ap dung vao phan tich co ban co phieu", "cơ cấu vốn capital structure là gì cách áp dụng vào phân tích cơ bản cổ phiếu"),
    ("co cau von", "cơ cấu vốn"),
    ("co cau", "cơ cấu"),
    ("co giau khong", "có giàu không"),
    ("co hoi thi truong la gi", "cơ hội thị trường là gì"),
    ("co hoi", "cơ hội"),
    ("co nen mua co phieu acb hay khong", "có nên mua cổ phiếu ACB hay không"),
    ("co nen mua co phieu acv hay khong", "có nên mua cổ phiếu ACV hay không"),
    ("co nen mua co phieu bid hay khong", "có nên mua cổ phiếu BID hay không"),
    ("co nen mua co phieu dig hay khong", "có nên mua cổ phiếu DIG hay không"),
    ("co nen mua co phieu frt hay khong", "có nên mua cổ phiếu FRT hay không"),
    ("co nen mua co phieu gas hay khong", "có nên mua cổ phiếu GAS hay không"),
    ("co nen mua co phieu hag hay khong", "có nên mua cổ phiếu HAG hay không"),
    ("co nen mua co phieu hpg hay khong", "có nên mua cổ phiếu HPG hay không"),
    ("co nen mua co phieu idj hay khong", "có nên mua cổ phiếu IDJ hay không"),
    ("co nen mua co phieu lpb hay khong", "có nên mua cổ phiếu LPB hay không"),
    ("co nen mua co phieu msb hay khong", "có nên mua cổ phiếu MSB hay không"),
    ("co nen mua co phieu mwg hay khong", "có nên mua cổ phiếu MWG hay không"),
    ("co nen mua co phieu oil", "có nên mua cổ phiếu OIL"),
    ("co nen mua co phieu pet hay khong", "có nên mua cổ phiếu PET hay không"),
    ("co nen mua co phieu plx hay khong", "có nên mua cổ phiếu PLX hay không"),
    ("co nen mua co phieu pnj hay khong", "có nên mua cổ phiếu PNJ hay không"),
    ("co nen mua co phieu pow hay khong", "có nên mua cổ phiếu POW hay không"),
    ("co nen mua co phieu ree hay khong", "có nên mua cổ phiếu REE hay không"),
    ("co nen mua co phieu sbt hay khong", "có nên mua cổ phiếu SBT hay không"),
    ("co nen mua co phieu scr hay khong", "có nên mua cổ phiếu SCR hay không"),
    ("co nen mua co phieu ssi hay khong", "có nên mua cổ phiếu SSI hay không"),
    ("co nen mua co phieu stb hay khong", "có nên mua cổ phiếu STB hay không"),
    ("co nen mua co phieu tar hay khong", "có nên mua cổ phiếu TAR hay không"),
    ("co nen mua co phieu tcb techcombank hay khong", "có nên mua cổ phiếu TCB Techcombank hay không"),
    ("co nen mua co phieu ttf hay khong", "có nên mua cổ phiếu TTF hay không"),
    ("co nen mua co phieu vcb vietcombank hay khong", "có nên mua cổ phiếu VCB Vietcombank hay không"),
    ("co nen mua co phieu vib hay khong 1", "có nên mua cổ phiếu VIB hay không 1"),
    ("co nen mua co phieu vib hay khong", "có nên mua cổ phiếu VIB hay không"),
    ("co nen mua co phieu vietnam airlines hvn hay khong", "có nên mua cổ phiếu Vietnam Airlines HVN hay không"),
    ("co nen mua co phieu vjc hay khong", "có nên mua cổ phiếu VJC hay không"),
    ("co nen mua co phieu vpb hay khong", "có nên mua cổ phiếu VPB hay không"),
    ("co nen mua co phieu", "có nên mua cổ phiếu"),
    ("co nen", "có nên"),
    ("co phieu bi cat margin nguyen nhan anh huong va cach xu ly", "cổ phiếu bị cắt margin nguyên nhân ảnh hưởng và cách xử lý"),
    ("co phieu blue chip la gi", "cổ phiếu blue chip là gì"),
    ("co phieu esop la gi", "cổ phiếu ESOP là gì"),
    ("co phieu la gi cac loai co phieu tren thi truong chung khoan viet nam", "cổ phiếu là gì các loại cổ phiếu trên thị trường chứng khoán Việt Nam"),
    ("co phieu otc la gi mua co phieu otc o dau", "cổ phiếu OTC là gì mua cổ phiếu OTC ở đâu"),
    ("co phieu phong thu la gi", "cổ phiếu phòng thủ là gì"),
    ("co phieu penny la gi", "cổ phiếu penny là gì"),
    ("co phieu quy la gi", "cổ phiếu quỹ là gì"),
    ("co phieu thuong la gi", "cổ phiếu thường là gì"),
    ("co phieu trang ben mua la gi", "cổ phiếu trắng bên mua là gì"),
    ("co phieu tru la gi", "cổ phiếu trừ là gì"),
    ("co phieu uu dai la gi", "cổ phiếu ưu đãi là gì"),
    ("co phieu vinfast mua o dau", "cổ phiếu VinFast mua ở đâu"),
    ("co tuc la gi", "cổ tức là gì"),
    ("co choi duoc chung khoan khong", "có chơi được chứng khoán không"),
    ("cong cu tai chinh pho bien tai viet nam", "công cụ tài chính phổ biến tại Việt Nam"),
    ("cong cu", "công cụ"),
    ("cong nghiep", "công nghiệp"),
    ("cong nghe hang dau the gioi", "công nghệ hàng đầu thế giới"),
    ("cong nghe", "công nghệ"),
    ("cong suc", "công sức"),
    ("cong ty co phan tap doan fpt", "công ty cổ phần tập đoàn FPT"),
    ("cong ty co phan tap doan", "công ty cổ phần tập đoàn"),
    ("cong ty co phan", "công ty cổ phần"),
    ("cong ty", "công ty"),
    ("copy trading hinh thuc giao dich tai chinh tiet kiem thoi gian va cong suc", "copy trading hình thức giao dịch tài chính tiết kiệm thời gian và công sức"),
    ("cung tien la gi", "cung tiền là gì"),
    ("cung tien", "cung tiền"),
    ("current ratio la gi cach tinh va y nghia cua he so nay", "current ratio là gì cách tính và ý nghĩa của hệ số này"),
    # D
    ("danh gia va cap nhat ket qua kinh doanh moi nhat", "đánh giá và cập nhật kết quả kinh doanh mới nhất"),
    ("danh gia va ket qua kinh doanh moi nhat", "đánh giá và kết quả kinh doanh mới nhất"),
    ("danh gia va", "đánh giá và"),
    ("danh gia", "đánh giá"),
    ("danh sach day du va cap nhat nam 2024", "danh sách đầy đủ và cập nhật năm 2024"),
    ("danh sach day du", "danh sách đầy đủ"),
    ("danh sach", "danh sách"),
    ("dau tu chung khoan cho nguoi moi bat dau", "đầu tư chứng khoán cho người mới bắt đầu"),
    ("dau tu chung khoan", "đầu tư chứng khoán"),
    ("dau tu tien ao tu a z cho f0 tranh mat tien", "đầu tư tiền ảo từ A đến Z cho F0 tránh mất tiền"),
    ("dau tu tien ao", "đầu tư tiền ảo"),
    ("dau tu", "đầu tư"),
    ("day du va cap nhat nam", "đầy đủ và cập nhật năm"),
    ("day du", "đầy đủ"),
    ("dieu can biet truoc khi tham gia thi truong chung khoan", "điều cần biết trước khi tham gia thị trường chứng khoán"),
    ("dinh gia co phieu cho nguoi moi bat dau", "định giá cổ phiếu cho người mới bắt đầu"),
    ("dinh gia phan tich ky thuat va ket qua kinh doanh moi nhat", "định giá phân tích kỹ thuật và kết quả kinh doanh mới nhất"),
    ("dinh gia ket qua kinh doanh moi nhat", "định giá kết quả kinh doanh mới nhất"),
    ("dinh gia", "định giá"),
    ("doanh nghiep dang bi dinh gia thap", "doanh nghiệp đang bị định giá thấp"),
    ("doanh nghiep", "doanh nghiệp"),
    ("duoc chung khoan khong", "được chứng khoán không"),
    ("duoc", "được"),
    ("duong ma pho bien trong phan tich ky thuat", "đường MA phổ biến trong phân tích kỹ thuật"),
    ("duong ma pho bien", "đường MA phổ biến"),
    ("duong ma", "đường MA"),
    # G
    ("giao dich chung khoan quan trong ma nguoi moi can biet", "giao dịch chứng khoán quan trọng mà người mới cần biết"),
    ("giao dich tai chinh tiet kiem thoi gian va cong suc", "giao dịch tài chính tiết kiệm thời gian và công sức"),
    ("giao dich tai chinh", "giao dịch tài chính"),
    ("giao dich", "giao dịch"),
    ("giau khong", "giàu không"),
    # H
    ("hang dau the gioi", "hàng đầu thế giới"),
    ("hanh nghe chung khoan la gi", "hành nghề chứng khoán là gì"),
    ("hanh nghe", "hành nghề"),
    ("hay khong", "hay không"),
    ("he so nay", "hệ số này"),
    ("he so", "hệ số"),
    ("hieu qua", "hiệu quả"),
    ("hieu ro ve vn index vn 30 hnx index va nhieu chi so khac", "hiểu rõ về VN-Index VN-30 HNX-Index và nhiều chỉ số khác"),
    ("hieu ro ve", "hiểu rõ về"),
    ("hieu ro", "hiểu rõ"),
    ("hinh thuc giao dich tai chinh tiet kiem", "hình thức giao dịch tài chính tiết kiệm"),
    ("hinh thuc", "hình thức"),
    ("hoa phat hpg nhanh chong va an toan", "Hòa Phát HPG nhanh chóng và an toàn"),
    ("huong dan moi nhat 2024", "hướng dẫn mới nhất 2024"),
    ("huong dan moi nhat", "hướng dẫn mới nhất"),
    # K
    ("ket qua kinh doanh moi nhat", "kết quả kinh doanh mới nhất"),
    ("ket qua kinh doanh", "kết quả kinh doanh"),
    ("ket qua", "kết quả"),
    ("kien thuc dsc", "kiến thức DSC"),
    ("khong", "không"),
    # L
    ("la gi", "là gì"),
    ("lam gi khi bi call margin", "làm gì khi bị call margin"),
    ("loai co phieu tren thi truong chung khoan viet nam", "loại cổ phiếu trên thị trường chứng khoán Việt Nam"),
    ("loai co phieu", "loại cổ phiếu"),
    ("loai tai khoan chung khoan pho bien tai viet nam", "loại tài khoản chứng khoán phổ biến tại Việt Nam"),
    ("loai tai khoan", "loại tài khoản"),
    ("loai", "loại"),
    ("loi nhuan gop la gi y nghia cua bien loi nhuan gop khi lua chon co phieu", "lợi nhuận gộp là gì ý nghĩa của biên lợi nhuận gộp khi lựa chọn cổ phiếu"),
    ("loi nhuan gop", "lợi nhuận gộp"),
    ("loi nhuan rong", "lợi nhuận ròng"),
    ("loi nhuan", "lợi nhuận"),
    ("loi suat trai phieu", "lợi suất trái phiếu"),
    ("lua chon co phieu", "lựa chọn cổ phiếu"),
    # M
    ("mau hinh pho bien", "mẫu hình phổ biến"),
    ("mai phuc", "mai phục"),
    ("moi nhat 2025", "mới nhất 2025"),
    ("moi nhat 2024", "mới nhất 2024"),
    ("moi nhat", "mới nhất"),
    ("mo tai khoan chung khoan my", "mở tài khoản chứng khoán Mỹ"),
    ("mua co phieu online cho nguoi moi bat dau", "mua cổ phiếu online cho người mới bắt đầu"),
    ("mua co phieu ipo", "mua cổ phiếu IPO"),
    ("mua o dau", "mua ở đâu"),
    ("muc dich cua viec chia tach co phieu", "mục đích của việc chia tách cổ phiếu"),
    # N
    ("nam 2025", "năm 2025"),
    ("nam 2024", "năm 2024"),
    ("nen dung app nao", "nên dùng app nào"),
    ("nen dung", "nên dùng"),
    ("nen kinh te va thi truong chung khoan", "nền kinh tế và thị trường chứng khoán"),
    ("nen kinh te", "nền kinh tế"),
    ("nha dau tu", "nhà đầu tư"),
    ("nhanh chong va an toan", "nhanh chóng và an toàn"),
    ("nhan dinh va cap nhat ket qua kinh doanh moi nhat", "nhận định và cập nhật kết quả kinh doanh mới nhất"),
    ("nhan dinh va ket qua kinh doanh moi nhat", "nhận định và kết quả kinh doanh mới nhất"),
    ("nhan dinh va cap nhat ket qua", "nhận định và cập nhật kết quả"),
    ("nhan dinh va ket qua kinh d", "nhận định và kết quả kinh d"),
    ("nhan dinh", "nhận định"),
    ("nhieu chi so khac", "nhiều chỉ số khác"),
    ("niem yet thuoc tap doan vingroup danh sach day du va cap nhat nam 2024", "niêm yết thuộc tập đoàn Vingroup danh sách đầy đủ và cập nhật năm 2024"),
    ("niem yet", "niêm yết"),
    ("noi bat", "nổi bật"),
    ("nguoi moi bat dau", "người mới bắt đầu"),
    ("nguoi moi can biet", "người mới cần biết"),
    ("nguoi moi", "người mới"),
    ("nguyen nhan anh huong va cach xu ly", "nguyên nhân ảnh hưởng và cách xử lý"),
    ("nguyen nhan", "nguyên nhân"),
    ("nguyen tac giao dich cua richard donchian", "nguyên tắc giao dịch của Richard Donchian"),
    ("nguyen tac", "nguyên tắc"),
    ("ngan hang", "ngân hàng"),
    ("nhung dieu can biet truoc khi tham gia thi truong chung khoan", "những điều cần biết trước khi tham gia thị trường chứng khoán"),
    # O
    ("o dau", "ở đâu"),
    # P
    ("phan tich co ban trong chung khoan", "phân tích cơ bản trong chứng khoán"),
    ("phan tich co ban co phieu", "phân tích cơ bản cổ phiếu"),
    ("phan tich co ban", "phân tích cơ bản"),
    ("phan tich bao cao tai chinh quan trong nhat cho nha dau tu", "phân tích báo cáo tài chính quan trọng nhất cho nhà đầu tư"),
    ("phan tich bao cao tai chinh", "phân tích báo cáo tài chính"),
    ("phan tich ky thuat co phieu la gi cach giao dich va cac mau hinh pho bien", "phân tích kỹ thuật cổ phiếu là gì cách giao dịch và các mẫu hình phổ biến"),
    ("phan tich ky thuat co phieu", "phân tích kỹ thuật cổ phiếu"),
    ("phan tich ky thuat", "phân tích kỹ thuật"),
    ("phan tich tai chinh", "phân tích tài chính"),
    ("phan tich", "phân tích"),
    ("pho bien tai viet nam", "phổ biến tại Việt Nam"),
    ("pho bien trong phan tich ky thuat", "phổ biến trong phân tích kỹ thuật"),
    ("pho bien", "phổ biến"),
    ("phong tranh trong phan tich ky thuat", "phòng tránh trong phân tích kỹ thuật"),
    ("phong thu la gi", "phòng thủ là gì"),
    ("phong thu", "phòng thủ"),
    # Q
    ("quan trong ma nguoi moi can biet", "quan trọng mà người mới cần biết"),
    ("quan trong nhat cho nha dau tu", "quan trọng nhất cho nhà đầu tư"),
    ("quan trong", "quan trọng"),
    ("quy dinh giao dich chung khoan quan trong ma nguoi moi can biet", "quy định giao dịch chứng khoán quan trọng mà người mới cần biết"),
    ("quy dinh", "quy định"),
    # S
    ("san chung khoan hose hnx upcom", "sàn chứng khoán HOSE HNX UPCOM"),
    ("san chung khoan", "sàn chứng khoán"),
    ("san xuat cong nghiep iip la gi", "sản xuất công nghiệp IIP là gì"),
    ("san xuat cong nghiep", "sản xuất công nghiệp"),
    ("san xuat", "sản xuất"),
    ("su dung", "sử dụng"),
    # T
    ("tac dong cua bom tien den ttck", "tác động của bơm tiền đến TTCK"),
    ("tac dong cua cau tien toi nen kinh te va thi truong chung khoan", "tác động của cầu tiền tới nền kinh tế và thị trường chứng khoán"),
    ("tac dong cua", "tác động của"),
    ("tac dong den", "tác động đến"),
    ("tai chinh tiet kiem thoi gian va cong suc", "tài chính tiết kiệm thời gian và công sức"),
    ("tai chinh", "tài chính"),
    ("tai khoan chung khoan my", "tài khoản chứng khoán Mỹ"),
    ("tai khoan chung khoan", "tài khoản chứng khoán"),
    ("tai khoan", "tài khoản"),
    ("tang gia de dau tu", "tăng giá để đầu tư"),
    ("tang gia trong thi truong chung khoan", "tăng giá trong thị trường chứng khoán"),
    ("tang gia", "tăng giá"),
    ("tap doan vingroup", "tập đoàn Vingroup"),
    ("tap doan fpt", "tập đoàn FPT"),
    ("tap doan", "tập đoàn"),
    ("tham gia thi truong chung khoan", "tham gia thị trường chứng khoán"),
    ("tham gia thi truong", "tham gia thị trường"),
    ("thanh toan bop la gi", "thanh toán BOP là gì"),
    ("thanh toan", "thanh toán"),
    ("the gioi", "thế giới"),
    ("thi phan", "thị phần"),
    ("thi truong chung khoan viet nam", "thị trường chứng khoán Việt Nam"),
    ("thi truong chung khoan", "thị trường chứng khoán"),
    ("thi truong", "thị trường"),
    ("thoi gian va cong suc", "thời gian và công sức"),
    ("thoi gian", "thời gian"),
    ("thuat ngu trong chung khoan", "thuật ngữ trong chứng khoán"),
    ("thuat ngu", "thuật ngữ"),
    ("thuoc tap doan vingroup", "thuộc tập đoàn Vingroup"),
    ("thuong mai la gi vai tro va tac dong den nen kinh te", "thương mại là gì vai trò và tác động đến nền kinh tế"),
    ("thuong mai", "thương mại"),
    ("tien ao tu a z cho f0 tranh mat tien", "tiền ảo từ A đến Z cho F0 tránh mất tiền"),
    ("tien ao", "tiền ảo"),
    ("tiet kiem thoi gian va cong suc", "tiết kiệm thời gian và công sức"),
    ("tiet kiem", "tiết kiệm"),
    ("tim hieu chi tiet ve loi suat trai phieu", "tìm hiểu chi tiết về lợi suất trái phiếu"),
    ("tim hieu chi tiet ve chi phi co dinh trong kinh doanh", "tìm hiểu chi tiết về chi phí cố định trong kinh doanh"),
    ("tim hieu chi tiet ve", "tìm hiểu chi tiết về"),
    ("tim hieu", "tìm hiểu"),
    ("tong quan danh gia va cap nhat ket qua kinh doanh moi nhat", "tổng quan đánh giá và cập nhật kết quả kinh doanh mới nhất"),
    ("tong quan danh gia va ket qua kinh doanh moi nhat", "tổng quan đánh giá và kết quả kinh doanh mới nhất"),
    ("tong quanh danh gia va cap nhat ket qua kinh doanh moi nhat", "tổng quan đánh giá và cập nhật kết quả kinh doanh mới nhất"),
    ("tong quanh danh gia va ket qua kinh doanh moi nhat", "tổng quan đánh giá và kết quả kinh doanh mới nhất"),
    ("tong quan nhan dinh va cap nhat ket qua kinh doanh moi nhat", "tổng quan nhận định và cập nhật kết quả kinh doanh mới nhất"),
    ("tong quan nhan dinh va ket qua kinh doanh moi nhat", "tổng quan nhận định và kết quả kinh doanh mới nhất"),
    ("tong quan dinh gia phan tich ky thuat va ket qua kinh doanh moi nhat", "tổng quan định giá phân tích kỹ thuật và kết quả kinh doanh mới nhất"),
    ("tong quan dinh gia ket qua kinh doanh moi nhat", "tổng quan định giá kết quả kinh doanh mới nhất"),
    ("tong quan dinh gia", "tổng quan định giá"),
    ("tong quan danh gia va", "tổng quan đánh giá và"),
    ("tong quan nhan dinh va", "tổng quan nhận định và"),
    ("tong quanh", "tổng quan"),
    ("tong quan", "tổng quan"),
    ("tot va co tiem nang tang gia de dau tu", "tốt và có tiềm năng tăng giá để đầu tư"),
    ("tot va co tiem nang tang gia", "tốt và có tiềm năng tăng giá"),
    ("tot", "tốt"),
    ("trang ben mua la gi", "trắng bên mua là gì"),
    ("tren san hnx", "trên sàn HNX"),
    ("tren san hose", "trên sàn HOSE"),
    ("tren san upcom", "trên sàn UPCOM"),
    ("tren thi truong chung khoan viet nam", "trên thị trường chứng khoán Việt Nam"),
    ("tren", "trên"),
    ("truoc khi tham gia thi truong chung khoan", "trước khi tham gia thị trường chứng khoán"),
    ("tru la gi", "trừ là gì"),
    ("tu nhan", "tư nhân"),
    # U
    ("uu dai la gi", "ưu đãi là gì"),
    ("uu dai", "ưu đãi"),
    # V
    ("va cap nhat ket qua kinh doanh moi nhat", "và cập nhật kết quả kinh doanh mới nhất"),
    ("va cap nhat ket qua", "và cập nhật kết quả"),
    ("va cach xu ly", "và cách xử lý"),
    ("va co tiem nang tang gia de dau tu", "và có tiềm năng tăng giá để đầu tư"),
    ("va co tiem nang tang gia", "và có tiềm năng tăng giá"),
    ("va ket qua kinh doanh moi nhat", "và kết quả kinh doanh mới nhất"),
    ("va ket qua kinh doanh", "và kết quả kinh doanh"),
    ("va nhieu chi so khac", "và nhiều chỉ số khác"),
    ("va thi truong chung khoan", "và thị trường chứng khoán"),
    ("va y nghia quan trong trong thi truong chung khoan viet nam", "và ý nghĩa quan trọng trong thị trường chứng khoán Việt Nam"),
    ("va y nghia quan trong", "và ý nghĩa quan trọng"),
    ("vang lai la gi", "vãng lai là gì"),
    ("vang lai", "vãng lai"),
    ("viet nam", "Việt Nam"),
    ("von capital structure", "vốn capital structure"),
    ("von capex", "vốn capex"),
    ("von", "vốn"),
    # X
    ("xac dinh va phong tranh trong phan tich ky thuat", "xác định và phòng tránh trong phân tích kỹ thuật"),
    ("xac dinh", "xác định"),
    ("xu huong tang gia trong thi truong chung khoan", "xu hướng tăng giá trong thị trường chứng khoán"),
    ("xu huong tang gia", "xu hướng tăng giá"),
    ("xu huong", "xu hướng"),
    ("xu ly", "xử lý"),
    # Y
    ("y nghia cua bien loi nhuan gop khi lua chon co phieu", "ý nghĩa của biên lợi nhuận gộp khi lựa chọn cổ phiếu"),
    ("y nghia cua bien loi nhuan gop", "ý nghĩa của biên lợi nhuận gộp"),
    ("y nghia cua chi so dow jones", "ý nghĩa của chỉ số Dow Jones"),
    ("y nghia cua he so nay", "ý nghĩa của hệ số này"),
    ("y nghia cua he so", "ý nghĩa của hệ số"),
    ("y nghia cua", "ý nghĩa của"),
    ("y nghia va cach su dung", "ý nghĩa và cách sử dụng"),
    ("y nghia va cach tinh chi phi von", "ý nghĩa và cách tính chi phí vốn"),
    ("y nghia va cach tinh", "ý nghĩa và cách tính"),
    ("y nghia quan trong trong thi truong chung khoan viet nam", "ý nghĩa quan trọng trong thị trường chứng khoán Việt Nam"),
    ("y nghia quan trong", "ý nghĩa quan trọng"),
    ("y nghia", "ý nghĩa"),
]

# Sort longest patterns first so specific multi-word phrases match before shorter fallbacks
REPLACEMENTS.sort(key=lambda x: len(x[0]), reverse=True)

# Add standalone fallback patterns (after sort so they come last)
REPLACEMENTS += [
    ('co phieu', 'cổ phiếu'),
    ('chi so', 'chỉ số'),
    ('chung khoan', 'chứng khoán'),
    ('theo doi', 'theo dõi'),
    ('chuyen vien', 'chuyên viên'),
    ('chuyen sau', 'chuyên sâu'),
    ('chuyen', 'chuyên'),
    ('an toan', 'an toàn'),
    ('nhanh chong', 'nhanh chóng'),
    ('nen dung', 'nên dùng'),
    ('ap luc', 'áp lực'),
    ('co ban', 'cơ bản'),
    ('lai suat', 'lãi suất'),
    ('chung khoan', 'chứng khoán'),
    ('trai phieu', 'trái phiếu'),
    ('san giao dich', 'sàn giao dịch'),
    ('nha nuoc', 'nhà nước'),
    ('kinh te', 'kinh tế'),
    ('tai san', 'tài sản'),
    ('tiep can', 'tiếp cận'),
    ('bao cao tai chinh', 'báo cáo tài chính'),
    # Industry / sector terms (safe replacements specific to finance content)
    ('chuoi gia tri', 'chuỗi giá trị'),
    ('nganh bat dong san', 'ngành bất động sản'),
    ('nganh ban le', 'ngành bán lẻ'),
    ('nganh bao hiem', 'ngành bảo hiểm'),
    ('nganh cao su', 'ngành cao su'),
    ('nganh dau khi', 'ngành dầu khí'),
    ('nganh det may', 'ngành dệt may'),
    ('nganh dien', 'ngành điện'),
    ('nganh hoa chat', 'ngành hóa chất'),
    ('nganh nang luong', 'ngành năng lượng'),
    ('nganh ngan hang', 'ngành ngân hàng'),
    ('nganh nhua', 'ngành nhựa'),
    ('nganh nong nghiep', 'ngành nông nghiệp'),
    ('nganh o to', 'ngành ô tô'),
    ('nganh phan bon', 'ngành phân bón'),
    ('nganh thep', 'ngành thép'),
    ('nganh thuy san', 'ngành thủy sản'),
    ('nganh van tai', 'ngành vận tải'),
    ('nganh xay dung', 'ngành xây dựng'),
    ('nganh cong nghe', 'ngành công nghệ'),
    ('nganh cong nghiep', 'ngành công nghiệp'),
    ('nganh du lich', 'ngành du lịch'),
    ('nganh', 'ngành'),
    ('gia tri', 'giá trị'),
    ('bat dong san', 'bất động sản'),
    ('ban le', 'bán lẻ'),
    ('bao hiem', 'bảo hiểm'),
    ('dau khi', 'dầu khí'),
    ('det may', 'dệt may'),
    ('hoa chat', 'hóa chất'),
    ('nang luong', 'năng lượng'),
    ('nong nghiep', 'nông nghiệp'),
    ('phan bon', 'phân bón'),
    ('thuy san', 'thủy sản'),
    ('van tai', 'vận tải'),
    ('xay dung', 'xây dựng'),
]

# Pre-compile patterns (case-insensitive, Unicode word boundary)
COMPILED = [
    (re.compile(r'(?<!\w)' + re.escape(src) + r'(?!\w)', re.IGNORECASE | re.UNICODE), dst)
    for src, dst in REPLACEMENTS
]


def apply_replacements(text: str) -> str:
    for pat, dst in COMPILED:
        text = pat.sub(dst, text)
    return text


def fix_live_published_row(line: str) -> str:
    if '| Live Published |' not in line:
        return line

    parts = line.split('|')
    if len(parts) < 5:
        return line

    anchor = parts[1].strip()
    url = parts[2].strip()

    # Strip all existing Vietnamese diacritics so replacements apply cleanly
    normalized = remove_viet_diacritics(anchor)
    fixed_anchor = apply_replacements(normalized)

    # Rebuild keywords as: [fixed_anchor], kiến thức DSC
    fixed_keywords = fixed_anchor + ', kiến thức DSC'

    parts[1] = f' {fixed_anchor} '
    parts[3] = f' {fixed_keywords} '

    return '|'.join(parts)


def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    fixed_lines = []
    changed = 0
    for line in lines:
        fixed = fix_live_published_row(line)
        if fixed != line:
            changed += 1
        fixed_lines.append(fixed)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.writelines(fixed_lines)

    print(f'Done. {changed} rows modified out of {len(lines)} lines.', file=sys.stderr)


if __name__ == '__main__':
    main()
